networks:

  backend:
    driver: bridge

services:
  badminton-api:
    build: ./api  # badminton-api 모듈에 있는 Dockerfile을 빌드
    ports:
      - "8080:8080"  # API 서비스의 포트
    networks:
      - backend
    image: speech2/badminton:api

  badminton-batch:
    build: ./batch  # badminton-batch 모듈에 있는 Dockerfile을 빌드
    ports:
      - "9090:9090"
    networks:
      - backend
    image: speech2/badminton:batch
