networks:
  backend:
    driver: bridge

services:
  badminton-api:
    build:
      context: ./api
    platform: linux/amd64  # x86 아키텍처
    ports:
      - "8080:8080"
    networks:
      - backend
    image: speech2/badminton:api

  badminton-batch:
    build:
      context: ./batch
    platform: linux/amd64  # x86 아키텍처
    ports:
      - "9090:9090"
    networks:
      - backend
    image: speech2/badminton:batch

  badminton-admin:
    build:
      context: ./admin
    platform: linux/amd64  # x86 아키텍처
    ports:
      - "8090:8090"
    networks:
      - backend
    image: speech2/badminton:admin