networks:

  backend:
    driver: bridge

services:

  badminton-api:
    build: ./badminton-api  # badminton-api 모듈에 있는 Dockerfile을 빌드
    ports:
      - "8080:8080"  # API 서비스의 포트
    networks:
      - backend

  badminton-batch:
    build: ./badminton-batch  # badminton-batch 모듈에 있는 Dockerfile을 빌드
    ports:
      - "9090:9090"
    networks:
      - backend